# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: "template_project_name"
version: "0.0.1"
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: "template_project_name"

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# metrics:

models:
  template_project_name:
    +persist_docs:
      relation: true
      columns: true

    intermediate:
      +materialized: ephemeral
      +schema: intermediate

    marts:
      +materialized: table
      +schema: analytics

    staging:
      +materialized: view
      +schema: staging

seeds:
  template_project_name:
    +schema: seeds
    +persist_docs:
      relation: true
      columns: true

# semantic-models:

snapshots:
  template_project_name:
    +schema: snapshots
    +persist_docs:
      relation: true
      columns: true
# sources:

# tests:

# vars:

# on-run-start: sql-statement | [sql-statement]
# on-run-end: sql-statement | [sql-statement]

# restrict-access: true | false
